# fly.toml app configuration file generated for mina-tanja-recipe-search on 2023-12-02T16:39:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mina-tanja-recipe-search"
primary_region = "lhr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]